import React, { useState } from "react";
import { logo } from "../assets/images";
import jsPDF from 'jspdf';
// import 'jspdf-autotable'; 
import { FaBars } from "react-icons/fa";
import { RxCross2 } from "react-icons/rx";
import { NavLink } from "react-router-dom";
import { FaAngleDown } from "react-icons/fa";
function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };
  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.text('Hello world!', 10, 10);
    doc.text('This is a PDF generated by jsPDF.', 10, 20);
    doc.save('example.pdf');
  };

  return (
    <div>
      <div className=" bg-black">
        <div className="flex justify-end max-w-screen-xl mx-auto py-1 px-10">
          <NavLink
            to="/login"
            className="cursor-pointer hover:text-blue-500 hover:underline text-base bg-red-500 text-white px-5 py-1 rounded-sm "
          >
            Login
          </NavLink>
        </div>
      </div>
      <div className="w-full h-24 bg-slate-50">
        <div className="max-w-screen-xl mx-auto h-full bg-slate-50 flex justify-between px-12 sm:px-10 items-center">
          <div>
            <NavLink to={"/"}>
              <img src={logo} alt="Logo" className="h-32 mix-blend-darken" />
            </NavLink>
          </div>
          <div className="lg:hidden">
            {menuOpen ? (
              <RxCross2
                className="text-2xl cursor-pointer"
                onClick={toggleMenu}
              />
            ) : (
              <FaBars
                className="text-2xl cursor-pointer"
                onClick={toggleMenu}
              />
            )}
          </div>
          <div
            className={`${
              menuOpen ? "flex" : "hidden"
            } lg:flex flex-col lg:flex-row absolute lg:static top-24 left-0 w-full lg:w-auto bg-slate-200 lg:bg-transparent`}
          >
            <ul className="flex flex-col lg:flex-row items-center gap-8 font-medium p-5 lg:p-0">
              <NavLink
                to="/"
                className="cursor-pointer hover:text-blue-500 hover:underline text-sm"
              >
                Home
              </NavLink>
              <NavLink
                to="/about"
                className="cursor-pointer hover:text-blue-500 hover:underline text-sm"
              >
                About
              </NavLink>
              <li className="relative group cursor-pointer hover:text-blue-500 text-sm flex items-center gap-1">
                Services
                <FaAngleDown />
                <ul className="absolute top-5 left-0  w-48 rounded-md bg-white shadow-lg hidden group-hover:block z-10">
                  <li>
                    <NavLink className="block px-4 py-2  text-sm">{""}</NavLink>
                    <NavLink
                      to="/online/service1"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Comprehensive property management
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/online/service2"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Custom property management
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/online/service3"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Property management services
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/online/service4"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Security of property
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/online/service5"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Rent management
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/online/service6"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Legal services
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/online/service7"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Property dispute redressal
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/online/service8"
                      className="block px-4 py-2 hover:bg-gray-100 rounded-b-lg text-sm"
                    >
                      Fresh properties
                    </NavLink>
                  </li>
                </ul>
              </li>
              <li className="relative group cursor-pointer hover:text-blue-500 text-sm flex items-center gap-1">
                Financial Services
                <FaAngleDown />
                <ul className="absolute top-3 rounded-lg left-0 mt-2 w-48 bg-white shadow-lg hidden group-hover:block z-10">
                  <li>
                    <NavLink
                      to=""
                      className="block px-4 py-2 text-sm"
                    ></NavLink>
                    <NavLink
                      to="/financial/commercial-finance"
                      className="block px-4 py-2 hover:bg-gray-100 r text-sm"
                    >
                      Commercial Finance
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/financial/project-finance"
                      className="block px-4 py-2 hover:bg-gray-100 rounded-b-lg text-sm"
                    >
                      Project Finance
                    </NavLink>
                  </li>
                </ul>
              </li>
              <li className="relative group cursor-pointer hover:text-blue-500 text-sm flex items-center gap-1">
                Online services
                <FaAngleDown />
                <ul className="absolute top-3 rounded-lg left-0 mt-2 w-48 bg-white shadow-lg hidden group-hover:block z-10">
                  <li>
                    <NavLink
                      to=""
                      className="block px-4 py-2 text-sm"
                    ></NavLink>
                    <NavLink
                      to="/rent-agreement"
                      className="block px-4 py-2 hover:bg-gray-100 rounded-b-lg text-sm"
                    >
                      Rent Agreement
                    </NavLink>
                  </li>
                </ul>
              </li>
              <li className="relative group cursor-pointer hover:text-blue-500 text-sm flex items-center gap-1">
                Location
                <FaAngleDown />
                <ul className="absolute top-3 rounded-lg left-0 mt-2 w-48 bg-white shadow-lg hidden group-hover:block z-10">
                  <li>
                    <NavLink
                      to=""
                      className="block px-4 py-2 text-sm"
                    ></NavLink>
                    <NavLink
                      to="/location/noida"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Noida
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/location/delhi"
                      className="block px-4 py-2 hover:bg-gray-100 text-sm"
                    >
                      Delhi
                    </NavLink>
                  </li>
                  <li>
                    <NavLink
                      to="/location/kolkata"
                      className="block px-4 py-2 rounded-b-lg hover:bg-gray-100 text-sm"
                    >
                      Kolkata
                    </NavLink>
                  </li>
                </ul>
              </li>
              <NavLink
                to="/contact"
                className="cursor-pointer hover:text-blue-500 text-sm hover:underline"
              >
                Contact
              </NavLink>

              <li className="relative group cursor-pointer hover:text-blue-500 text-sm flex items-center gap-1">
  Location
  <FaAngleDown />
  <ul className="absolute top-3 rounded-lg left-0 mt-2 w-48 bg-white shadow-lg hidden group-hover:block z-10">
    <li>
      <a
        href="/path/to/pdf1.pdf"  // Replace with the actual path to your PDF
        download
        className="block px-4 py-2 text-sm"
      >
        pdf1
      </a>
    </li>
    <li>
      <a
        href="/path/to/pdf2.pdf"  // Replace with the actual path to your PDF
        download
        className="block px-4 py-2 hover:bg-gray-100 text-sm"
      >
        pdf2
      </a>
    </li>
    <li>
      <a
        href="/path/to/pdf3.pdf"  // Replace with the actual path to your PDF
        download
        className="block px-4 py-2 rounded-b-lg hover:bg-gray-100 text-sm"
      >
        pdf3
      </a>
    </li>
  </ul>
</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Header;
